export enum ApiErrorCode {
  EMPTY_REQUEST_BODY = "EMPTY_REQUEST_BODY",
  INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",
  SOMETHING_BAD_HAPPENED = "SOMETHING_BAD_HAPPENED",
  UNAUTHORIZED = "UNAUTHORIZED",
  //Login
  EMAIL_DOES_NOT_EXISTS = "EMAIL_DOES_NOT_EXISTS",
  WRONG_PASSWORD = "WRONG_PASSWORD",
  BANNED = "BANNED",
  //Register
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  OTP_CODE_NOT_VALID = "OTP_CODE_NOT_VALID",
}
